---
### **1. Vectorization**
---
#### ***1.1. Vector Product***

In [1]:
import numpy as np

In [2]:
l = [1,5,6,2] # list

In [3]:
lol = [[1,5,6,2], # list of lists
        [3,2,1,3]]

In [4]:
lolol = [[[1,5,6,2], # list of lists of lists
        [3,2,1,3]],
        [[5,2,1,2],
        [6,4,8,4]],
        [[2,8,5,3],
        [1,1,9,4]]]

In [5]:
lols = [[4,2,3], # this is not an array but list of lists as it is not a homologous list with equal dimension
        [5,1]]

In [18]:
len(lols[1])

2

In [11]:
l = [[[3,2], [4,5]],[[3,4],[2,3]]]
print(len(l[1]))

2


In [19]:
li_matrix = [[4,2], 
             [5,1], 
             [8,2]]
print(len(li_matrix))

3


In [22]:
x = np.array(li_matrix)
print(x.shape)

(3, 2)


In [32]:
print(len(lolol))
print(len(lolol[0]))
print(len(lolol[2][1]))

3
2
4


In [26]:
arr = np.array(lolol) # 3D array
print(arr.shape)

(3, 2, 4)


In [33]:
inputs = [1,2,3,4]
weight = [0.4,0.7,0.3,1.9]
bias = 2.3

x = np.dot(weight,inputs) +bias
print(x)

12.600000000000001


---
##### 1.1.1. ***One Layer***
---

In [52]:
inputs = [1,2, 3, 4.5]
weight = [[1.2, 1.5, 0.2, 0.5], 
          [0.3, 0.6, 0.1, 0.8], 
          [0.1, 0.5, 1.5, 0.3]]
bias = [0.1, 0.4, 0.2]
#inputs = np.array(inputs)
#weight = np.array(weight)
#bias = np.array(bias)
outputs = np.dot(weight, inputs)
print(outputs)

[7.05 5.4  6.95]


In [53]:
a = [1,2,3]
b = [[1,2,3],
    [2,3,4],
    [9,7,3]]
a = np.array(a)
b = np.array(b)
#what is the np.dot product of (a,b) and (b, a)?

In [54]:
prod = np.dot(a,b)
prod1 = np.dot(b,a)

In [55]:
print(prod)
print(prod1)

[32 29 20]
[14 20 32]


---
##### **Multiply Matrix and Vector**
---
- Multiplications are only possible if the row of first matrix is similar with column of the second matrix

$ \begin{pmatrix}
a & b & c \\
d & e & f \\
g & h & i \\
\end{pmatrix}$ $ * $ $\begin{pmatrix}
j \\
k \\
l \\
\end{pmatrix}$ $\Rightarrow $ $ j$ * $\begin{pmatrix} a\\d\\g\\\end{pmatrix}$ + $k $* $ \begin{pmatrix} b\\e\\h\\\end{pmatrix}$ +$l $* $ \begin{pmatrix} c\\f\\i\\\end{pmatrix}$
---
##### **Multiply Vector by Matrix**
---
$\begin{equation}
  \begin{bmatrix}
    a & b & c 
  \end{bmatrix}
  *
  \begin{bmatrix}
    x & y & z \\
    w & u & t \\
    g & i & o \\
  \end{bmatrix} 
\end{equation}$ $\Rightarrow $ $\sum \begin{bmatrix}
    a \\
    b \\
    c \\
  \end{bmatrix}$$ *  $$\begin{bmatrix}
    y \\
    u \\
    i \\
  \end{bmatrix}$, $\ldots$  ,$\sum \begin{bmatrix}
    a \\
    b \\
    c \\
  \end{bmatrix}$$ *  $$\begin{bmatrix}
    z \\
    t \\
    o \\
  \end{bmatrix}$
---
---