---
### **Fully Connected Dense Layer**
---
- **It is a dense or fully-connected layer**
- **Weights are initialized randomly in usual cases unless you will use the pretrained model**
- **Weights are initialized by** ***(inputs, neurons)*** **instead of** ***(neurons, inputs)*** **to prevent the transposition of weights**
- **Biases are usually initialized with zero, why? like many samples values containing zero its preferable to put biases as 0, to make those neurons fires**
- **Based on some senarios like when the** ***(weight.inputs + biases)*** **not meet the activation function threshold gives the output to zero from neuron**
- **This will result in the inputs multiplied by this neuron output will be zero resulting in** ***DEAD NEURON*** **that's why we need BACKPROPAGATION and modification of biases**

In [1]:
class DenseLayer():
    def __init__(self, inputs, nneurons):
        pass
    def forward(self):
        pass

In [2]:
import numpy as np

---
#### ***Class Dense Layer***
---
- **Initialize weights using** ***(np.random.randn)*** **and multiply** **with** ***(0.01)*** **and** ***(np.zeros)*** **for biases**
- **np.random.randn() produces a Gaussian distribution with a mean of 0 and a variance of 1, which means that it’ll generate random numbers, positive and negative, centered at 0 and with the mean value close to 0**
- **neural networks work best with values between -1 and +1**
- **Multiply this Gaussian distribution for the weights by 0.01 to generate numbers that are a couple of magnitudes smaller.**
- **Otherwise, the model will take more time to fit the data during the training process as starting values will be disproportionately large compared to the updates being made during training.**
- **np.zeros function takes a desired array shape as an argument and returns an array of that shape filled with zeros.**

In [3]:
x = np.random.randn(2, 5)
print(x)

[[-1.31212147  0.68334118  0.272628   -0.38867187  0.25888587]
 [ 1.00941942  0.69817204  2.19594382 -1.77923207 -0.95523158]]


In [4]:
y = np.zeros((2, 5))
print(y)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [5]:
class DenseLayer:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.01*np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases
    

In [6]:
import nnfs
from nnfs.datasets import spiral_data
nnfs.init()

In [7]:
X, y = spiral_data(samples=100, classes=3)
print(X.shape)

(300, 2)


In [8]:
dense1 = DenseLayer(2, 3)
dense1.forward(X)
print(dense1.output[:5])

[[ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [-1.0475188e-04  1.1395361e-04 -4.7983500e-05]
 [-2.7414842e-04  3.1729150e-04 -8.6921798e-05]
 [-4.2188365e-04  5.2666257e-04 -5.5912682e-05]
 [-5.7707680e-04  7.1401405e-04 -8.9430439e-05]]
