---
#### **Optimizers**
---
- SGD-fits a single sample at a time.
- MBGD-is used to fit slices of a dataset, which we’d call batches in our context.
- BGD-is an optimizer used to fit a whole dataset at once.
---

In [ ]:
class SGD:
    """
    """
    def __init__(self, learning_rate = 1):

        self.learning_rate = learning_rate
    def update_params(self, layer):
        layer.weights += -self.learning_rate*layer.weights
        layer.biases += -self.learning_rate*layer.biases
        

$\begin{array}{l}\begin{bmatrix} \frac{\partial f_{1}}{\partial x_{1}} & \frac{\partial f_{1}}{\partial x_{2}} & \cdots &\frac{\partial f_{1}}{\partial x_{m}} \\ \frac{\partial f_{2}}{\partial x_{1}}& \frac{\partial f_{2}}{\partial x_{2}} & \cdots & \frac{\partial f_{2}}{\partial x_{m}}\\ \frac{\partial f_{3}}{\partial x_{1}}& \frac{\partial f_{3}}{\partial x_{2}} &\cdots & \frac{\partial f_{3}}{\partial x_{m}} \end{bmatrix}\end{array}$

In [1]:
import numpy as np
softmax_output = [0.7, 0.1, 0.2]

In [3]:
softmax_output = np.array(softmax_output).reshape(-1,1)
print(softmax_output)

[[0.7]
 [0.1]
 [0.2]]


In [9]:
print(softmax_output.shape[0])

3


In [7]:
print(np.eye(softmax_output.shape[0]))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
